USE college;
DROP TABLE IF EXISTS DEPT;
DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPT (
    DEPTNO INT,
    DNAME VARCHAR(20),
    LOC VARCHAR(20)
);
RENAME TABLE DEPT TO DEPARTMENT;
ALTER TABLE DEPARTMENT
ADD PINCODE INT NOT NULL DEFAULT 0;
ALTER TABLE DEPARTMENT
CHANGE DNAME DEPT_NAME VARCHAR(20);
ALTER TABLE DEPARTMENT
MODIFY LOC CHAR(10);
DROP TABLE DEPARTMENT;
SHOW TABLES;
DESC DEPARTMENT;
SELECT * FROM DEPARTMENT;
SELECT DATABASE();
